sample_list: "config/samples.tsv"
barcode_list: "config/barcodes.tsv"
# Subunits to analyse, currently only 16S and 18S are supported
subunits:
  - "16S"
  - "18S"
# Sequences per spots
seqs_per_spot: 100
UMI:
  start: 18
  stop: 25
taxtool: "vsearch"
vsearch:
  cutoff: 0.0
  16S: "https://www.drive5.com/sintax/rdp_16s_v18.fa.gz"
  18S: "https://www.drive5.com/sintax/silva_18s_v123.fa.gz"
assignTaxonomy:
  minBoot: 50
  outputBootstraps: True
  tryRC: True
  taxdb:
    #RDP: https://zenodo.org/record/4310151/files/rdp_train_set_18.fa.gz?download=1
    #GTDB: https://zenodo.org/record/2541239/files/GTDB_bac-arc_ssu_r86.fa.gz?download=1
    #SILVA: https://zenodo.org/record/4587955/files/silva_nr99_v138.1_train_set.fa.gz?download=1
    #SBDI-curated: https://scilifelab.figshare.com/ndownloader/files/28624482
    16S: "https://scilifelab.figshare.com/ndownloader/files/28624482"
    18S: "https://github.com/pr2database/pr2database/releases/download/v4.14.0/pr2_version_4.14.0_SSU_dada2.fasta.gz"
  speciesdb:
    16S: "https://scilifelab.figshare.com/ndownloader/files/28624479"
