$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  sample_list:
    type: string
    description: "Path to a sample sheet"
    default: "config/samples.tsv"
  sortmerna:
    type: object
    properties:
      evalue:
        type: number
        description: "E-value threshold for sortmerna"
        default: 0.0000000001
  subunits:
    type: array
    description: "Subunits to run analysis for"
    default:
      - "16S"
      - "18S"
    items:
      enum: ["16S", "18S"]
  vsearch:
    type: object
    default:
      cutoff: 0.0
      16S: "https://www.drive5.com/sintax/rdp_16s_v18.fa.gz"
      18S: "https://www.drive5.com/sintax/silva_18s_v123.fa.gz"
    properties:
      cutoff:
        type: number
        description: "Sintax cutoff"
      16S:
        type: string
        description: "URL to sintax 16S db"
      18S:
        type: string
        description: "URL to sintax 18S db"
  metaxa2:
    type: object
    default:
      score_cutoff: 50
      domains:
        - eukaryota
      cutoffs: "0,60,70,70,75,85,90,95"
      percent_id: 95
      lengt: 100
    properties:
      cutoffs:
        type: string
        description: Taxonomic cutoff string to use with Metaxa2 (-T option)
      score_cutoff:
        type: integer
        description: Minimum reliability score for filtering Metaxa2 hits
      percent_id:
        type: integer
        description: Minimum percent identity for filtering Metaxa2 hits
      length:
        type: integer
        description: Minimum alignment length for filtering Metaxa2 hits
  assignTaxonomy:
    type: object
    default:
      minBoot: 0
      outputBootstraps: True
      tryRC: False
    properties:
      database:
        type: object
        default:
          16S: "https://zenodo.org/record/2541239/files/GTDB_bac-arc_ssu_r86.fa.gz?download=1"
          18S: "https://github.com/pr2database/pr2database/releases/download/v4.14.0/pr2_version_4.14.0_SSU_dada2.fasta.gz"
      minBoot:
        type: integer
        description: "Number of bootstraps to run for assignTaxonomy"
      outputBootstraps:
        type: boolean
        description: "Whether to output bootstraps for assignTaxonomy"
