$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  sample_list:
    type: string
    description: "Path to a sample sheet"
    default: "config/samples.tsv"