sample_list: "config/samples.tsv"
barcode_list: "config/barcodes.tsv"
cutadapt:
  R1_adapter: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  R2_adapter: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  minlen: 20
  extra_params: "-e 0.3"
fastp:
  complexity_cutoff: 30
  extra_params: ""
# Subunits to analyse, currently only 16S and 18S are supported
sortmerna:
  evalue: 0.0000000001
subunits:
  - "16S"
  - "18S"
# Sequences per spots
seqs_per_spot: 0
UMI:
  start: 18
  stop: 25
taxtool: "assignTaxonomy"
vsearch:
  cutoff: 0.0
  16S: "https://www.drive5.com/sintax/rdp_16s_v18.fa.gz"
  18S: "https://www.drive5.com/sintax/silva_18s_v123.fa.gz"
assignTaxonomy:
  minBoot: 0
  outputBootstraps: True
  tryRC: False
  threads: 20
  taxdb:
    16S: "https://scilifelab.figshare.com/ndownloader/files/28624482"
    18S: "https://github.com/pr2database/pr2database/releases/download/v4.14.0/pr2_version_4.14.0_SSU_dada2.fasta.gz"
  speciesdb:
    16S: "https://scilifelab.figshare.com/ndownloader/files/28624479"
    18S: "https://github.com/pr2database/pr2database/releases/download/v4.14.0/pr2_version_4.14.0_SSU_UTAX.fasta.gz"
  ranks:
    16S: ["superkingdom", "phylum", "class", "order", "family", "genus"]
    18S: ["kingdom", "supergroup", "division", "class", "order", "family", "genus"]
metaxa2:
  # Reliability score cutoff for taxonomic assignments
  score_cutoff: 0
  # Minimum percent identity to trust taxonomic assignments
  percent_id: 95
  # Minimum alignment length for trusted classifications
  length: 100
  taxdb:
    18S: "https://github.com/pr2database/pr2database/releases/download/v4.14.0/pr2_version_4.14.0_SSU_dada2.fasta.gz"